version: "3.9"

services:
  laravelapp:
    container_name: laravelapp
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: management-uin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
